### ISSUE TITLE
17 Apr 2019 Tech Talks Lite

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#35]
@ertzeid will hang out for an informal AMA!

- MC: TBD [The MC’s GitHub username]

## Todo for the MC:

- [ ] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [ ] Update the 18F Events calendar entry for this event to add the talk details.
- [ ] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [ ] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Enable phone-in option for those using FedRelay.
- [ ] Upload video.
