### ISSUE TITLE
5 Jun 2019 Tech Talk: GCP Pilot Project

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#36]
GCP Pilot Project

- Presenter: @timothy-spencer 
- MC: @davemcorwin 

## Todo for the MC:

- [x] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [ ] Update the 18F Events calendar entry for this talk to add the talk details.
- [ ] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable phone-in option for those using FedRelay.
- [x] Upload video.

**Comment by davemcorwin** [comment]
The audio and video are now available: https://drive.google.com/drive/folders/1Bw3ejA8_93sRBitAw4qoJebqYAGBvUIR
