### ISSUE TITLE
Tech Talks Lite proposal

### ISSUE THREAD

**Issue by mgwalker** [18F/tech-talks#37]
# Tech Talk Submission

Thanks for offering to give a talk at a Tech Talks meeting! We just need a bit of information from you.

## Name

@mgwalker

## What's your talk title?

What is Charlie?

## What's your talk about?

Charlie, our plastic pal who's fun to be with, is a Hubot instance running some custom scripts. What's it written in? Where does it live? How does it get started? Who can contribute to it? Where can I find out more?

## How long is your talk?

- [X] Lightning talk (5-10 minutes)
- [ ] Short tech talk (20-25 minutes)
- [ ] Long tech talk (40-50 minutes)

## Todo for the MC:

- [x] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [x] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [x] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [x] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by geekygirlsarah** [comment]
Presented on Nov 23, 2021!
