### ISSUE TITLE
19 June 2019 Tech Talk: Assisted Acquisition Authority

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/tech-talks#38]
What it is and how we can use it.

- Presenters: @abisker @AshleyO85 
- MC: @tadhg-ohiggins 

## Todo for the MC:

- [x] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [x] Update the 18F Events calendar entry for this talk to add the talk details.
- [ ] Ask the parties responsible for the Engineering Chapter newsletter for that week to add details about the talk(s) to the newsletter.
- [ ] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Enable phone-in option for those using FedRelay.
- [ ] Upload video.
