### ISSUE TITLE
17 July 2019 Tech Talk: What's new with Github presented by Jamie Jones (Github)

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#39]
# What's new with Github
Jamie Jones from Github will fill us in on the latest and greatest on Github followed by Q&A.

- Presenter: Jamie Jones (external)
- MC: @davemcorwin 

## Todo for the MC:

- [x] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [x] Update the 18F Events calendar entry for this talk to add the talk details.
- [ ] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [x] Get speaker approval
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable phone-in option for those using FedRelay.
- [x] Upload video.

**Comment by davemcorwin** [comment]
Video available https://drive.google.com/drive/folders/1f9NNq1Hj138VWpJOIEQd8wQXGUl2njyD

Great success!
