### ISSUE TITLE
14 August 2019 Tech Talk: Secure Logging for Kubernetes by Mike Lloyd pt. 1

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#40]
I wanted to walk the community through deploying the Open Distro for Elasticsearch (ODfE) in Kubernetes as the core logging provider. I had a use case for Secure Logging in k8s, and I wanted to share my pain and struggled with the community so others can learn from my pain and suffering.

- Presenter: @mxplusb 
- MC: @davemcorwin 

## Todo for the MC:

- [x] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [x] Update the 18F Events calendar entry for this talk to add the talk details.
- [x] Ask the parties responsible for the Engineering Chapter newsletter for that week to add details about the talk(s) to the newsletter.
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable phone-in option for those using FedRelay.
- [x] Upload video.
