### ISSUE TITLE
04 September 2019 Tech Talk: Why do people use Drupal anyway and how to survive if you’re suddenly on a Drupal project by Fureigh Rhys

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#41]
Why do people use Drupal anyway and how to survive if you’re suddenly on a Drupal project

- Presenter: @fureigh 
- MC: @davemcorwin 

## Todo for the MC:

- [x] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [x] Update the 18F Events calendar entry for this talk to add the talk details.
- [x] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable phone-in option for those using FedRelay.
- [x] Upload video.
