### ISSUE TITLE
21 August 2019 Tech Talk: Prototype to production: the eApp story by Ryan Hofschneider

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#42]
Prototype to production: the eApp story
This talk will be a condensed treatment of the 3-year eApp project – an assisted acquisition at 18F, with OPM and DISA as partners. 
The presentation will focus on topics and lessons most relevant to the Engineering Chapter and the theme of the past year of work: get eApp into production at DISA, navigating all the technical, political, compliance, and contractual hurdles, as well as the challenges inherent in a new program office.

- Presenter: @ryanhofdotgov 
- MC: @davemcorwin 

## Todo for the MC:

- [x] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [x] Update the 18F Events calendar entry for this talk to add the talk details.
- [x] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable phone-in option for those using FedRelay.
- [x] Upload video.
