### ISSUE TITLE
02 October 2019 Tech Talk: Get to know login.gov

### ISSUE THREAD

**Issue by lauraGgit** [18F/tech-talks#43]
With a lot of new engineers coming onboard getting to know the what and the why of login.gov, as you may be coming across partners who would like to manage identity verification and authentication (mostly for the public) to their applications.

- Presenter: @lauraGgit 
- MC: @davemcorwin 

## Todo for the MC:

- [x] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [x] Update the 18F Events calendar entry for this talk to add the talk details.
- [x] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable phone-in option for those using FedRelay.
- [x] Upload video.

**Comment by davemcorwin** [comment]
https://drive.google.com/drive/folders/1XWqvVCkV-OEaCRZmTKpo4pqvKwtN-zYN
