### ISSUE TITLE
2019-10-23 Tech Talk special edition: Consulting on Path Analyses

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/tech-talks#46]
(This is a “special edition” talk because it's happening on what would normally be a tech talks off week.)
@coreycaitlin will talk to us about path analysis consulting.

- Presenter: @coreycaitlin
- MC: @tadhg-ohiggins 

## Todo for the MC:

- [ ] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [x] Update the 18F Events calendar entry for this talk to add the talk details.
- [ ] Ask the parties responsible for the Engineering Chapter newsletter for that week to add details about the talk(s) to the newsletter.
- [ ] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Enable phone-in option for those using FedRelay.
- [ ] Upload video.
