### ISSUE TITLE
2019-11-20 Tech Talk: Before Projects Start

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/tech-talks#47]
This will be a more interactive talk, with Hannah asking us about what we need/want to know before projects start and how account managers can work with us on that.

- Presenter: @hannahkane 
- MC: @davemcorwin 

## Todo for the MC:

- [x] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [x] Update the 18F Events calendar entry for this talk to add the talk details.
- [ ] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable phone-in option for those using FedRelay.
- [x] Upload video.

**Comment by hannahkane** [comment]
@tadhg-ohiggins - can you please let me know what time this tech talk is scheduled for? I can't seem to find the 18F Events calendar. Thanks!

**Comment by hannahkane** [comment]
This happened! Mural used is here: https://app.mural.co/t/gsa6/m/gsa6/1571759805290/95605d7c9c7980c62f9e8b5e7cd5dcadbefc76b1

**Comment by davemcorwin** [comment]
Video and audio uploaded to https://drive.google.com/drive/folders/1jQ18YUwwD8BTI8CRr5X3Zk97sAqskzts
