### ISSUE TITLE
2020-02-05 Tech Talk: Trello with firewalled partners via a cloud.gov Trello proxy

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#48]
@pburkholder 

Short (15m?) talk on using a lightweight Nginx reverse-proxy on cloud.gov as "cloud-access security broker." This enables firewalled agencies to use Trello when on an engagement with us. And collaborating with the network and security team establishes a pattern for how they can assess and use SaaS.

- Presenter: @pburkholder 
- MC: @davemcorwin 

## Todo for the MC:

- [x] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [x] Update the 18F Events calendar entry for this talk to add the talk details.
- [x] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [x] Upload video.

**Comment by pburkholder** [comment]
@davemcorwin Updated.

**Comment by davemcorwin** [comment]
Unscheduled

**Comment by davemcorwin** [comment]
Thanks @pburkholder !!! Assets can be found in https://drive.google.com/drive/folders/1US3TEvFTy4vWfMSl28EYvhtNXrrn9gh-
