### ISSUE TITLE
2019-12-04 Tech Talk: Efficiently Using VoiceOver with Web applications

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#49]
In a joint effort with the Accessibility Guild, @Jacklynn and @iamjolly will help us learn how to effectively use the Voice Over screen reader utility to navigate a website

- Presenter: @Jacklynn @iamjolly 
- MC: @davemcorwin 

## Todo for the MC:

- [x] Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).
- [x] Update the 18F Events calendar entry for this talk to add the talk details.
- [ ] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [x] Upload video.

**Comment by Jacklynn** [comment]
@davemcorwinI I can schedule captioning today using the info on the tech-talk calendar event so I can announce with for the a11y guild! Flag if you want me to wait or anything.

**Comment by davemcorwin** [comment]
https://drive.google.com/drive/folders/1SbsY6UBdIgGcn-jINFpiMKHSJyBkdJak

**Comment by iamjolly** [comment]
Deck added to the Drive folder with the recording files moved to here: https://docs.google.com/presentation/d/1dFdaPYMyah8YjWM_3w_4yTJ2nM0IB0zgMT561QIJrME/edit?usp=sharing
