### ISSUE TITLE
2020-06-03 Tech Talk: What Engineers should know and why they should care about contracting

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#50]
Training for newer folks in government on how acquisition impacts their technical work 

- Presenter: @lauraGgit 
- MC: @davemcorwin 

## Todo for the MC:
- [x] Update Title/description (@lauraGgit )
- [x] ~Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).~
- [x] Update the TTS Events calendar entry for this talk to add the talk details.
- [ ] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [ ] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [x] Upload video.
