### ISSUE TITLE
2020-06-17 Tech Talk: Cloud.gov migrating to Redis on AWS ElastiCache

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#51]
Cloud.gov is migrating from self hosted Redis services to leveraging AWS ElastiCache Redis.  We'll talk about the differences between the two services, the pros and cons of leveraging an AWS managed service, and tips on migrating.

- Presenter: @apburnes
- MC: @davemcorwin 

## Todo for the MC:
- [X] Update Title/description (@apburnes )
- [x] ~Secure Zoom Pro Account (done via #admins-zoom on Slack, typically on the morning of the talk or the day before the talk).~
- [x] Update the TTS Events calendar entry for this talk to add the talk details.
- [x] Ask the parties responsible for the Engineering Chapter newsletter for that week to add details about the talk(s) to the newsletter.
- [ ] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [x] Upload video.
