### ISSUE TITLE
2020-07-15 Tech Talk: Mainframe Modernization in the Federal Government

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#52]
### An Iterative Approach to Modernizing Legacy Workloads

Big data is not new. It has been with us, in some form or another, since the 1950s. Punch card computing, magnetic storage and eventually Mainframes gave us the batched processing approach to data management that has worked for decades. And boy does it work. Once these solutions are implemented they keep working, and working; long after their creators are retired and lounging on a beach in Florida. So over the years, organizations developed modernization strategies that worked around the mainframe and implemented modern User Interfaces around legacy data. Eventually the workload becomes too complex to be limited by transactional delays. The roads off the mainframe are fraught with danger and technical debt. The decisions made now will echo across the organization. We'll discuss a few potential approaches to, repercussions of, and unique challenges presented in, implementing iterative modernization strategies in the federal government.

- Presenter: @adam-grandt-tts @UchMok 
- MC: @davemcorwin 

## Todo for the MC:

- [x] Update the TTS Events calendar entry for this talk to add the talk details.
- [x] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [x] Ask the parties responsible for the Engineering Chapter newsletter for that week to add details about the talk(s) to the newsletter.
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Upload video.

**Comment by adam-grandt-tts** [comment]
"Mainframe Modernization in the Federal Government" seems like a good open ended title
