### ISSUE TITLE
[On Hold] Tech Talk: Brokering for fun and profit - supplementing cloud.gov's service brokers

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#53]
A short description of your talk goes here. What kinds of things will we learn from this talk?

- Presenter: @mogul
- MC: @davemcorwin 

## Todo for the MC:

- [ ] Update the TTS Events calendar entry for this talk to add the talk details.
- [ ] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [ ] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [ ] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Upload video.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
