### ISSUE TITLE
2020-09-02 Tech Talk: Smartsheet Demo Day

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#54]
A short description of your talk goes here. What kinds of things will we learn from this talk?

- Presenter: @its-a-lisa-at-work 
- MC: @davemcorwin 

## Todo for the MC:

- [ ] Update the TTS Events calendar entry for this talk to add the talk details.
- [ ] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [ ] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [ ] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Upload video.

**Comment by davemcorwin** [comment]
https://drive.google.com/drive/folders/1KGOuMEy1eLgMSlKLKD3jE-5CEBXaLLuo
