### ISSUE TITLE
2020-12-16 Tech Talk: Getting started with pandas

### ISSUE THREAD

**Issue by davemcorwin** [18F/tech-talks#56]
A short description of your talk goes here. What kinds of things will we learn from this talk?

> [Pandas](https://pandas.pydata.org/) is a very handy tool for doing data analysis in Python. In this session, you'll get a taste of how to use pandas to work with data tables and, with just a bit of code, do things that are tough in spreadsheets.
>
> Some coding experience will be helpful, but isn't required.

- Presenter: @afeld 
- MC: @davemcorwin 

## Todo for the MC:

- [x] Update the TTS Events calendar entry for this talk to add the talk details.
- [x] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [ ] Ask the parties responsible for the Engineering Chapter newsletter for that week to add details about the talk(s) to the newsletter.
- [x] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Upload video to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by davemcorwin** [comment]
Caption meeting id 4665552

**Comment by afeld** [comment]
[Slides/workbook](https://colab.research.google.com/github/afeld/python-public-policy/blob/main/pandas_crash_course.ipynb)

**Comment by davemcorwin** [comment]
https://drive.google.com/drive/folders/1NHvwKqZIuzD4lAv67nRwY_h_YPLq1tSC

**Comment by davemcorwin** [comment]
thanks @afeld !
