### ISSUE TITLE
Tech Talks Lite #[index]

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/tech-talks#57]
- [Presenter 1 GitHub username] **[Talk title]**

  A short description of the talk goes here. What kinds of things will we learn from this talk?
  
- [Presenter 2 GitHub username] **[Talk title]**

  A short description of the talk goes here. What kinds of things will we learn from this talk?

- [Presenter 3 GitHub username] **[Talk title]**

  A short description of the talk goes here. What kinds of things will we learn from this talk?
  
- [Presenter 4 GitHub username] **[Talk title]**

  A short description of the talk goes here. What kinds of things will we learn from this talk?

- MC: [The MC’s GitHub username]

## Todo for the MC:

- [ ] Update the TTS Events calendar entry for this event to add the talk details.
- [ ] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [ ] Ask the parties responsible for the Engineering Chapter newletter for that week to add details about the talk(s) to the newsletter.
- [ ] Announce the talk(s) in #dev on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Upload video.

**Comment by geekygirlsarah** [comment]
Closing as I wanted to test something and this wasn't a real suggestion.
