### ISSUE TITLE
Tech Talks Lite: Advent of Code 2021

### ISSUE THREAD

**Issue by loganmeetsworld** [18F/tech-talks#58]
# Tech Talk Submission

Thanks for offering to give a talk at a Tech Talks meeting! We just need a bit of information from you.

## Name

@loganmeetsworld

## What's your talk title?

Advent of Code 2021

## What's your talk about?

I'd like to do a short talk (15 minutes) on [advent of code](https://adventofcode.com/) preferably right before it starts (December 1) to invite people to our Slack channel (advent-of-code-2021) and explain what makes it fun and a cool learning experience. I will share some of my favorite past problems and how I approach the challenges. 

## How long is your talk?

- [X] Lightning talk (5-10 minutes)
- [ ] Short tech talk (20-25 minutes)
- [ ] Long tech talk (40-50 minutes)

## Do you have any preferred dates for it?

<!-- Pick a 1st/3rd Wednesday of an upcoming month, or say no preference >

## Todo for the MC:

- [ ] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [ ] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [ ] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-accounce when date is set
- [ ] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by geekygirlsarah** [comment]
Presented on Nov 23, 2021!
