### ISSUE TITLE
Tech Talk Lite: A brief look at image servers

### ISSUE THREAD

**Issue by jduss4** [18F/tech-talks#60]
# Tech Talk Submission

## Name

Jessica (@jduss4 )

## What's your talk title?

A brief look at image servers (I can change this later, but I'm feeling unimaginative)

## What's your talk about?

I would be happy to talk for a few minutes about the concept of an image server, why they are useful, one specification (IIIF), and how they are being used by at least one part of the federal government.

I've only really worked with image servers that conform to the IIIF specification, although I have some basic knowledge about other types of image servers and could probably do a bit of research to get me to 10 minutes of talk, if a more general talk would be of greater interest.

## How long is your talk?

- [X] Lightning talk (5-10 minutes)
- [ ] Short tech talk (20-25 minutes)
- [ ] Long tech talk (40-50 minutes)

## Do you have any preferred dates for it?

No sooner than Dec 2021, please!

## Todo for the MC:

- [x] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [x] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [x] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-accounce when date is set
- [x] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by geekygirlsarah** [comment]
Presented on Nov 23, 2021!
