### ISSUE TITLE
Tech Talk: Generating Network Data with Aspen

### ISSUE THREAD

**Issue by beechnut** [18F/tech-talks#61]
# Tech Talk Submission

Thanks for offering to give a talk at a Tech Talks meeting! We just need a bit of information from you.

## Name

Matt Cloyd

## What's your talk title?

Generating Network Data with Aspen

## What's your talk about?

Over the last few years, I wrote Aspen, a language that's basically Markdown for networks—type some text, render it, and you have a graph database.

Since we don't use graph databases much at TTS, I want to introduce them and show how to use Aspen to build and analyze a network.

## How long is your talk?

I could do this as two separate talks—a lightning on graphs and Aspen and then a short talk on how to do network analysis to support consulting / engineering work at TTS. Or, it could be both those talks combined. Let me know if you have a preference.

- [x] Lightning talk (5-10 minutes)
- [x] Short tech talk (20-25 minutes)
- [ ] Long tech talk (40-50 minutes)

## Do you have any preferred dates for it?

No preference!

## Todo for the MC:

- [x] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [x] Request captioning
- [x] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [x] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).
