### ISSUE TITLE
Tech Talk: Functional programming in Python

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/tech-talks#63]
# Tech Talk Submission

Thanks for offering to give a talk at a Tech Talks meeting! We just need a bit of information from you.

## Name

Tadhg

## What's your talk title?

Functional programming in Python.

## What's your talk about?

*   Basics:
    *   Purity/side effects.
    *   Immutability.
    *   Testability.
    *   Composability.
* Python support: reasonable (but no tail recursion optimization so be careful with recursion).
* `map` versus list comprehensions.
* Where's `reduce`?
* `functools.partial`.
    *   Enables easier composition.
    *   Adds a lot of convenience.
    *   May change how you order your function arguments.
* `operator`, especially `operator.methodcaller`.
* `itertools`.
* Missing: compose, identity, etc.—third party options exist, including `toolz`
    *   Brief overview of toolz.

## How long is your talk?

- [ ] Lightning talk (5-10 minutes)
- [X] Short tech talk (20-25 minutes)
- [ ] Long tech talk (40-50 minutes)

## Do you have any preferred dates for it?

Tuesday 01 March 2022

## Todo for the MC:

- [x] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [x] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [x] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [x] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).
