### ISSUE TITLE
Tech Talk: A Primer on Functional Programming

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/tech-talks#64]
# Tech Talk Submission

Thanks for offering to give a talk at a Tech Talks meeting! We just need a bit of information from you.

## Name

Sarah Withee

## What's your talk title?

A Primer on Functional Programming

## What's your talk about?

Functional programming languages are gaining in popularity. If you’ve worked in object-oriented languages, you might be baffled at how they work. Maybe hearing the word “recursion” makes you want to scream. Or maybe you’ve just heard the hype and want to know what the hype is about.

In this talk, we will briefly explain what functional languages are, and go into some examples of tasks that these languages are suited for. We will look at the major languages in use today and see how they work. We’ll see some of the things they have in common, and the many things that make them distinctive. Finally, we’ll offer some suggestions on how to dive into learning these and using them on your own projects.

## How long is your talk?

- [ ] Lightning talk (5-10 minutes)
- [X] Short tech talk (20-25 minutes)
- [X] Long tech talk (40-50 minutes)
(can be either)

## Do you have any preferred dates for it?

Tues Feb 15

## Todo for the MC:

- [x] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [x] Enable Relay Conference Captioning (RCC) via [FedRelay](https://www.sprintrelay.com/federal).
- [x] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [x] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).
