### ISSUE TITLE
Tech Talk: Functional Programming in JavaScript

### ISSUE THREAD

**Issue by heymatthenry** [18F/tech-talks#67]
# Tech Talk Submission

Thanks for offering to give a talk at a Tech Talks meeting! We just need a bit of information from you.

## Your Name

Matt Henry

## What's your talk title?

Functional Programming in JavaScript

## What's your talk about?

The talk will cover: 

* A little bit of the history of JS to show where it got its FP roots
* features of the JavaScript language that support FP idioms (closures, first-class functions, `map`/`filter`/`reduce`)
* basic library-less implementation of FP concepts like function composition
* (possibly) a bit about how popular libraries like React & Redux are based on FP concepts, so you might be getting some benefits of FP even if you didn't realize it!

## How long is your talk?

- [ ] Lightning talk (5-10 minutes)
- [ ] Short tech talk (20-25 minutes)
- [x] Long tech talk (40-50 minutes)

## Do you have any preferred dates for it?

3/29 works. Otherwise, no preference.

## Todo for the MC:

- [x] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [x] Request captioning
- [x] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [x] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by julialeague** [comment]
We'll do 03/29! Thanks, @heymatthenry
