### ISSUE TITLE
Tech Talk: "Hop in the Hot Air Balloon: An Introduction to Smalltalk"

### ISSUE THREAD

**Issue by eric-gade** [18F/tech-talks#70]
# Tech Talk Submission

Thanks for offering to give a talk at a Tech Talks meeting! We just need a bit of information from you.

## Your Name

Eric Gade

## What's your talk title?

Hop in the Hot Air Balloon: An Introduction to Smalltalk

## What's your talk about?

I will provide an overview of the Smalltalk computing environment, beginning with a synopsis of the early history and motivations, and explanation of the general principles, a live demonstration of one or more current open source Smalltalk systems, and concluding remarks about Smalltalk's place in the contemporary world. I hope to leave time for a Q&A afterwards as well.

## How long is your talk?

- [ ] Lightning talk (5-10 minutes)
- [ ] Short tech talk (20-25 minutes)
- [X] Long tech talk (40-50 minutes)

## Do you have any preferred dates for it?
June 7th, 14th or later (these are on Tuesdays right? If not I can supply more dates)

## Todo for the MC:

- [x] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [ ] Request captioning for the event date
- [x] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [x] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by julialeague** [comment]
@eric-gade sorry we've been a bit dormant this summer! Do you have any new dates you'd like to reserve? These are usually on Tuesdays, but we might be flexible about the day of the week.

**Comment by geekygirlsarah** [comment]
and typically they've been 1pm PT/4pm ET, but maybe flexible there too. Hard to get people out of meetings, which is why they're usually later in the day.
