### ISSUE TITLE
Tech Talk: [Your Title Here]

### ISSUE THREAD

**Issue by geekygirlsarah** [18F/tech-talks#71]
# Tech Talk Submission

Thanks for offering to give a talk at a Tech Talks meeting! We just need a bit of information from you.

## Your Name

@jduss4 

## What's your talk title?

TBD

## What's your talk about?

XML

## How long is your talk?

- [ ] Lightning talk (5-10 minutes)
- [ ] Short tech talk (20-25 minutes)
- [ ] Long tech talk (40-50 minutes)

## Do you have any preferred dates for it?

TBD

## Todo for the MC:

- [ ] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [ ] Request captioning for the event date
- [ ] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [ ] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by julialeague** [comment]
@jduss4 Thanks for submitting a talk proposal. Since the dates you listed have passed, are you interested in giving this talk any time in the next few weeks/months?

**Comment by jduss4** [comment]
Hi @julialeague! I'm anticipating being a little bit busy in the next few weeks, but would late November or early December work for you all?

**Comment by geekygirlsarah** [comment]
Sounds good to me!

**Comment by julialeague** [comment]
Sure thing! We'll follow up when we're closer to November/December to see what dates will work. Thanks!

**Comment by julialeague** [comment]
Hi @jduss4! Really sorry we fell off without checking in with you earlier. Are you still interested in scheduling this talk? Let me know if you have any particular dates in mind, if so.

**Comment by jduss4** [comment]
Oh my!  This has become something of a running joke for me, because it has been so long since I started the talk and I have yet to finish it.  Could we just pick a date towards the end of May or early June and then I will solemnly promise to have it ready by then?  I can probably do it sooner if needed, too, I just have enough balls in the air right now I don't feel a strong urge to add another!

**Comment by julialeague** [comment]
I totally understand, and we don't need to schedule it on any particular date. Whatever works best for you is preferred! Since Eric is schedule to talk on May 23rd, maybe targeting the early June period is best. How does June 6th or June 12th sound? Preference between the two? (P.S. @geekygirlsarah, let me know if you have any conflicts with those dates!)

**Comment by jduss4** [comment]
June 12th sounds good!  I may be potentially OOO on June 6th!

**Comment by jduss4** [comment]
I just noticed on the calendar there's a Tech Talk on June 14th -- is that when the XML talk was ultimately scheduled?

**Comment by geekygirlsarah** [comment]
Yeah, it looks like you're the speaker for it. Is this date good?

**Comment by jduss4** [comment]
Yep!  Just wanted to make sure because I hadn't heard officially yet!  Thanks

**Comment by jduss4** [comment]
Hello!  I can still do June 14th if that works best for all of you, but I was just realizing that there are a bunch of events that day.  The UX summit (all day) is going at the same time, there's an OGC mandatory training, etc...would the following week potentially work for y'all instead?  June 20th or 21st?

**Comment by jduss4** [comment]
June 28th would be a wonderful afternoon for a Tech Talk!  I can't wait until it gets bumped again to July 11th so that it's an even year of planning this talk :)

**Comment by julialeague** [comment]
That works for me too! I went ahead and rescheduled the talk hold. Sarah and I will work on getting an announcement drafted and amplified in the near future (we'll check with you before putting it out though).
