### ISSUE TITLE
Tech Talk: An overview of terminal multiplexing with `tmux`

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/tech-talks#72]
## Your Name

Tadhg

## What's your talk title?

`tmux`: terminal multiplexing and why it's useful.

## What's your talk about?

`tmux` makes your terminal more powerful by adding sessions, scrollback, comprehensive window management inside a single OS-level window, and more. This talk will go through:

*   Attach/detach, so it’s independent from your terminal program, meaning that a Terminal or iTerm2 crash is very easy to recover from (and, in my experience, those crash way more than ``tmux``). This also means you can attach to a session on a remote machine, which can be extremely useful.
*   Dividing windows into panes, and communicating between the panes.
*   Scrollback—lots and lots of scrollback. With that scrollback you get copying with keyboard bindings and search. So if you need to pull something out of something you did at the command line, you can do that fairly easily.
*   It fully supports scripting, so not only can you set up your panes as you like, you can script doing it.
*   Its support for sessions, which contain windows, which contain panes, is extremely powerful and lets you divide up projects and concerns very effectively. That same support also gives you a way to easily move between topics or themes without having to leave a specific window, which is extremely useful for some workflows.

## How long is your talk?

- [ ] Lightning talk (5-10 minutes)
- [x] Short tech talk (20-25 minutes)
- [ ] Long tech talk (40-50 minutes)

## Do you have any preferred dates for it?

*   30 August 2022.
*   13 September 2022.
*   20 September 2022.
*   27 September 2022.

## Todo for the MC:

- [x] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [x] Request captioning for the event date
- [x] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [x] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [x] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by julialeague** [comment]
Would 9/14 or 9/21 work for you, by chance? It looks like those are good dates for my/Sarah's calendars. We can try moving things around if not!

**Comment by tadhg-ohiggins** [comment]
@julialeague Yes, I would be happy to do either of those!
