### ISSUE TITLE
Tech Talk: A deep(ish) dive into git

### ISSUE THREAD

**Issue by timoballard** [18F/tech-talks#73]
# Tech Talk Submission

Thanks for offering to give a talk at a Tech Talks meeting! We just need a bit of information from you.

## Your Name

@timoballard 

## What's your talk title?

A deep(ish) dive into git

## What's your talk about?

Details TBD, but likely an overview of how git works under the hood and/or some of the more advanced git tooling

## How long is your talk?

- [ ] Lightning talk (5-10 minutes)
- [x] Short tech talk (20-25 minutes)
- [x] Long tech talk (40-50 minutes)

## Do you have any preferred dates for it?

February-ish?

## Todo for the MC:

- [ ] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [ ] Request captioning for the event date
- [ ] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [ ] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by geekygirlsarah** [comment]
Sweet! We can try to schedule this around Feb. Typically these have been Tues/Weds, 4pm ET/1pm PT. is that ok?

**Comment by timoballard** [comment]
Yes those days/times should generally work for me!

**Comment by julialeague** [comment]
Hi @timoballard! Really sorry we fell off without checking in with you earlier. Are you still interested in scheduling this talk? Let me know if you have any particular dates in mind, if so.
