### ISSUE TITLE
Tech Talk: Intro to Web Components

### ISSUE THREAD

**Issue by eric-gade** [18F/tech-talks#74]
# Tech Talk Submission

Thanks for offering to give a talk at a Tech Talks meeting! We just need a bit of information from you.

## Your Name

Eric Gade

## What's your talk title?

Intro to Web Components

## What's your talk about?

The talk will cover vanilla, browser-native [web components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) -- what they are, how they work, and most importantly how to make them. Live coding and examples will make up a large part of the presentation. I am hoping to work in some examples that might use and/or be relevant to the USWDS team, since they have expressed some interest. The content is very much still a work in progress.

## How long is your talk?

- [ ] Lightning talk (5-10 minutes)
- [ ] Short tech talk (20-25 minutes)
- [X] Long tech talk (40-50 minutes)

## Do you have any preferred dates for it?

Tuesday April 4th is probably the earliest I can do it.

## Todo for the MC:

- [ ] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [ ] Request captioning for the event date
- [ ] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [ ] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by julialeague** [comment]
Hi @eric-gade! Really sorry we fell off without checking in with you earlier. Are you still interested in scheduling this talk? Let me know if you have any particular dates in mind, if so.

**Comment by eric-gade** [comment]
Hey @julialeague ! Are we still trying to keep these to Tuesdays? If so I think Tuesday May 23rd would work best (I still need some time to prepare)

**Comment by julialeague** [comment]
That's right, Eric! May 23rd should work great. We'll send out an invite to you and get it on the books if you're ok with that!

**Comment by julialeague** [comment]
That's no problem, @eric-gade! Currently, the TTS Guilds calendar is up-to-date with our talk schedule, so feel free to pick a Tuesday (or Wednesday, if needed) and let me know once you're ready to reschedule. Thanks!

**Comment by eric-gade** [comment]
Hi just an update from my end, I will be going on PPL soon so this will have to wait until September. Let's kick the can until after the IRL? 🤞

**Comment by julialeague** [comment]
Sure thing, @eric-gade! Congratulations, and we'll talk to you when you're back.
