### ISSUE TITLE
Tech Talk: An Intro to SheetSupport

### ISSUE THREAD

**Issue by beechnut** [18F/tech-talks#76]
## Your Name
Matt Cloyd

## What's your talk title?
An Intro to SheetSupport
Deep dive into SheetSupport and Google Sheets custom functions (possible sequel)

## What's your talk about?
[I just announced SheetSupport](https://gsa-tts.slack.com/archives/CBUUX8FKQ/p1689019678148349?thread_ts=1688587646.572699&cid=CBUUX8FKQ), a collection of spreadsheet functions that bring desirable functionality from Ruby's Enumerable and Rails' ActiveSupport Core Extensions into spreadsheets, in the service of readable, maintainable spreadsheets.

## How long is your talk?

- [ ] Lightning talk (5-10 minutes)
- [x] Short tech talk (20-25 minutes)
- [ ] Long tech talk (40-50 minutes) <-- The sequel, doing a deep dive into the internals, would be close to the full hour

## Do you have any preferred dates for it?

As soon as comfortable for y'all

## Todo for the MC:

- [ ] Update the TTS Guilds calendar entry for this talk to add the talk details.
- [ ] Request captioning for the event date
- [ ] Announce the talk(s) in #tech-talks, #dev, #18f, #18f-dev-announce when date is set
- [ ] Announce the talk(s) in same channels on Slack in the morning, and follow up with a reminder just before they're about to begin.
- [ ] Upload video and transcript to [Google Drive](https://drive.google.com/drive/folders/1HEc6rMvFvbeFb08KY5ohO3IXnygPChVk).

**Comment by julialeague** [comment]
This sounds great, @beechnut!

How does Tuesday, August 1 2023 @ 1PM ET sound for scheduling?

**Comment by beechnut** [comment]
@julialeague Let's do it!
